spring:
  application:
    name: construction
  datasource:
    url: jdbc:postgresql://localhost:5434/Construction
    #    url: jdbc:postgresql://construction:5432/Construction
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      host: localhost
      port: 6380
      #      host: redis
      #      port: 6379
      password: construction-redis-p@ss
      connect-timeout: 60000
      client-type: lettuce
  mail:
    host: smtp.gmail.com
    port: 587
    username: serxan.babayev.06@gmail.com
    password: klmp yxwd jtdz ptmn
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true

validation-code:
  expireDate: 5

security:
    key: "jvdIc8VZQrh6T17RAywe6e/3u7wQ/WEXIUuLD1FWYo01yQcjjmjOBfwY/KeHu5cBaNMeJI0pZIMOwNCQuVnMvQ=="
refresh-token:
  expiration: 2592000000
access-token:
    expiration: 600000

file:
  dir: ./uploads/files
  image:
    dir: ./uploads/images